const data = {
  products: [
    {
      _id: 1,
      name: 'Chotu ka shirt',
      category: 'Shirts',
      images: '/images/p1.jpg',
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      countInStock: 0,
    },
    {
      _id: 2,
      name: 'Papa ka Shirts',
      category: 'Shirts',
      images: '/images/p2.jpg',
      price: 100,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
      countInStock: 1,
    },
    {
      _id: 3,
      name: 'Mera Shirts',
      category: 'Shirts',
      images: '/images/p3.jpg',
      price: 200,
      brand: 'Puma',
      rating: 4.9,
      numReviews: 11,
      description: 'supreme quality product',
      countInStock: 10,
    },
    {
      _id: 4,
      name: 'Bauni ka Pant',
      category: 'Pants',
      images: '/images/p4.jpg',
      price: 78,
      brand: 'Nike',
      rating: 1.2,
      numReviews: 14,
      description: 'high quality product',
      countInStock: 11,
    },
    {
      _id: 5,
      name: 'Mera Pant',
      category: 'Pants',
      images: '/images/p5.jpg',
      price: 65,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      countInStock: 15,
    },
    {
      _id: 6,
      name: 'Papa ka Pant',
      category: 'Pants',
      images: '/images/p6.jpg',
      price: 139,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 17,
      description: 'high quality product',
      countInStock: 6,
    },
  ],
};

module.exports = data;
